version: '3'
services:
  book-service:
    build: ./book-service
    ports:
      - '3001:3000'
    depends_on:
      - mongo

  author-service:
    build: ./author-service
    ports:
      - '3002:3000'
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    ports:
      - '3003:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
