version: '3'
services:
  # Service to manage books
  book-service:
    build: ./book-service
    ports:
      - '3001:3000'
    depends_on:
      - mongo

  # Service to manage authors
  author-service:
    build: ./author-service
    ports:
      - '3002:3000'
    depends_on:
      - mongo

  # Service to manage users
  user-service:
    build: ./user-service
    ports:
      - '3003:3000'
    depends_on:
      - mongo

  # MongoDB service for storage
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

networks:
  default:
    driver: bridge

# This Docker Compose file defines the services used in the application.